- name: change route53
  route53:
    state: present
    zone: test-udacity-devops-karthik.com
    record: www.test-udacity-devops-karthik.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "865aae02-b675-485a-a2de-f3fbdb7aa36d"
